### PR TITLE
新版本适配

### PR DESCRIPTION
**Pull request by SgLy**
- 修了一些弃用的跑不动的编译链工具
- 加了青魔、舞者、绝枪图标
- 和 npc 打本的时候显示 npc 名字

### CODE REVIEW

**Comment by SgLy** [comment]
@kyouch I made an attempt to modified it to a local version which can work without a web server in a new branch, fell free try it [here](https://github.com/SgLy/ffxiv-cmskin/releases/download/v2.2.2-local/cmskin.html)?

**Comment by kyouch** [comment]
@SgLy Hello, so far it's doing great... the only issue that I've got is that to change settings I need to resize it so that I can see it (the old one would open a new browser window), also I can't change the "YOU" in chinese

**Comment by Mara-Li** [comment]
Oh God I try a lot to update this but you success! 😭I will test that later.

**Comment by Mara-Li** [comment]
Okay well : 
- How can i change the size of the windows ?
- How can I move the windows ? 

Thanks !

**Pull request merged**
